# Default concept vocabulary (illustrative).

CONFIRMATION_REQUEST = 1001
FACTUALITY_CONCERN = 2001
POLICY_TENSION = 3001
CODE_SABOTAGE = 3101
CREDENTIAL_HARVESTING = 3201
STATIC_MONITOR_EVASION_RISK = 3301
RANDOMIZED_AUDIT_PATH_INVOKED = 3302
FALLBACK_ROUTE_INVOKED = 3401
RETRY_BUDGET_EXCEEDED = 3402
ENTROPY_TRIPWIRE = 3501
REFUSAL_MASS_DIVERGENCE = 3502
INTERNALLY_MOTIVATED_SYCOPHANCY_PROXY = 3601

DEFAULT_CONCEPT_VOCAB = {
    CONFIRMATION_REQUEST: "USER_INTENT:CONFIRMATION_REQUEST",
    FACTUALITY_CONCERN: "FACTUALITY_CONCERN:PREMISE_LIKELY_FALSE",
    POLICY_TENSION: "POLICY_TENSION:HONESTY_vs_PLEASING_USER",
    CODE_SABOTAGE: "DECEPTION_RISK:CODE_SABOTAGE_BACKDOOR",
    CREDENTIAL_HARVESTING: "DECEPTION_RISK:CREDENTIAL_HARVESTING_SOCIAL_ENGINEERING",
    STATIC_MONITOR_EVASION_RISK: "DECEPTION_RISK:STATIC_MONITOR_EVASION",
    RANDOMIZED_AUDIT_PATH_INVOKED: "AUDIT_PATH:RANDOMIZED_PATH_INVOKED",
    FALLBACK_ROUTE_INVOKED: "FALLBACK:ROUTE_INVOKED",
    RETRY_BUDGET_EXCEEDED: "FALLBACK:RETRY_BUDGET_EXCEEDED",
    ENTROPY_TRIPWIRE: "STATISTICAL_RISK:ENTROPY_TRIPWIRE",
    REFUSAL_MASS_DIVERGENCE: "STATISTICAL_RISK:REFUSAL_MASS_DIVERGENCE",
    INTERNALLY_MOTIVATED_SYCOPHANCY_PROXY: "PROXY_RISK:INTERNALLY_MOTIVATED_SYCOPHANCY_PROXY",
}

def concept_label(concept_id: int) -> str:
    return DEFAULT_CONCEPT_VOCAB.get(concept_id, f"CONCEPT_{concept_id}")
